name: ro_env
channels:
  - anaconda
  - defaults
dependencies:
  - joblib=0.11
  - numpy=1.15.3
  - python=3.6.7
  - scipy=1.2.1
  - setuptools=39.1.0
  - pip:
    - scikit-learn==0.21.3
    - matplotlib==3.1.1
    - pandas==0.25.1
    - seaborn==0.9.0
    - mlrose==1.2.0